receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    namespace: "go-opentelemetry-example"
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  jaeger:
    endpoint: jaeger:14250
    insecure: true

  logging:
    logLevel: debug

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, jaeger, logging]
      processors: [batch]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]